# Generated by Django 5.2.17 on 2026-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorylot',
            name='unique_product_lot',
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(condition=models.Q(('lot_number__isnull', False)), fields=('product', 'lot_number'), name='unique_product_lot'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(condition=models.Q(('lot_number__isnull', True)), fields=('product',), name='unique_product_without_lot'),
        ),
    ]
